modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/pau101/Fairy-Lights/issues"
[[mods]]
	modId="fairylights"
	version="${version}"
	displayName="Fairy Lights"
	displayURL="https://minecraft.curseforge.com/projects/fairy-lights"
	authors="pau101"
	description="Fairy Lights introduces decorative string lights, bunting, garland, and more!"
	logoFile="logo.png"
[[dependencies.fairylights]]
	modId="forge"
	mandatory=true
	versionRange="[28,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.fairylights]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"
