modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/pau101/Fairy-Lights/issues"
[[mods]]
	modId="fairylights"
	version="${version}"
	displayName="Fairy Lights"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/fairy-lights"
	authors="pau101"
	description="Fairy Lights introduces decorative string lights, bunting, garland, and more!"
	logoFile="logo.png"
[[dependencies.fairylights]]
	modId="forge"
	mandatory=true
	versionRange="[31,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.fairylights]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.15.2]"
	ordering="NONE"
	side="BOTH"
